server:
  port: ${PORT:1997}

api:
  base:
    path: 'api/v1'

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/fullstack_db}
    username: ${SPRING_DATASOURCE_USERNAME:fullstack}
    password: ${SPRING_DATASOURCE_PASSWORD:fullstack}
    driverClassName: com.mysql.cj.jdbc.Driver