server:
  port: ${PORT:1997}

api:
  base:
    path: 'api/v1'

spring:
  datasource:
    url: ${DB_CONNECTION_STR}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver