name: Multimodule project
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-local-image:
    name: Run endpoint tests against normal Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Log into DockerHub
        uses: docker/login-action@v3
        with:
          username: emmanuelu17
          password: ${{ secrets.MULTI_MODULE }}

      - name: Set up Docker Build
        run: docker build --tag normal-image:latest . --progress=plain

      - name: Build native docker image
        run: docker build --tag native-image:latest -f Dockerfile.native . --progress=plain

      - name: Run normal image tests
        run: |
          cd integration/
          mvn clean test -Dtest="IntegrationTest"

      - name: Run native image tests
        run: |
          cd integration/
          mvn clean test -Dtest="NativeImageTest"

#  build:
#    name: Run endpoint tests against normal Docker image
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout source code
#        uses: actions/checkout@v4
#
#      - name: Setup java 21
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'temurin'
#          java-version: '21'
#          cache: 'maven'
#
#      - name: Run tests
#        run: |
#          cd integration/
#          mvn clean test -Dtest="IntegrationTest"
#
#  build-native-image:
#    name: Run endpoint tests against native executable image
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout source code
#        uses: actions/checkout@v4
#
#      - name: Setup java 21
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'temurin'
#          java-version: '21'
#          cache: 'maven'
#
#      - name: Run tests
#        run: |
#          cd integration/
#          mvn clean test -Dtest="NativeImageTest"