name: Multimodule project
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  fullstack-module:
    name: Run endpoint tests against natively compiled fullstack module
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Run tests
        run: |
          mvn clean install -DskipTests
          cd integration/
          mvn test -Dtest="FullStackModuleTest"

  webserver-module:
    name: Run endpoint tests against natively compiled webserver module
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup GraalVM java 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'

      - name: Run Tests
        run: |
          mvn clean install -DskipTests
          cd integration/
          mvn test -Dtest="WebServerModuleTest"